
// This file has been generated by the GUI designer. Do not modify.
namespace KPI
{
	public partial class CreateJobWindow
	{
		private global::Gtk.VBox vboxMain;
		private global::Gtk.Label labelTitle;
		private global::Gtk.Entry entryTitle;
		private global::Gtk.Label labelDescription;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textDescription;
		private global::Gtk.Label labelDeadline;
		private global::Gtk.CheckButton checkIndefinitely;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Calendar calendarDeadline;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button buttonOk;
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KPI.CreateJobWindow
			this.Name = "KPI.CreateJobWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Creating job");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Dialog);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			// Container child KPI.CreateJobWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.Xalign = 0F;
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Title:");
			this.vboxMain.Add (this.labelTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.labelTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.entryTitle = new global::Gtk.Entry ();
			this.entryTitle.CanFocus = true;
			this.entryTitle.Name = "entryTitle";
			this.entryTitle.IsEditable = true;
			this.entryTitle.MaxLength = 511;
			this.entryTitle.InvisibleChar = '•';
			this.vboxMain.Add (this.entryTitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.entryTitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelDescription = new global::Gtk.Label ();
			this.labelDescription.Name = "labelDescription";
			this.labelDescription.Xalign = 0F;
			this.labelDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.vboxMain.Add (this.labelDescription);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.labelDescription]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textDescription = new global::Gtk.TextView ();
			this.textDescription.CanFocus = true;
			this.textDescription.Name = "textDescription";
			this.textDescription.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textDescription);
			this.vboxMain.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.GtkScrolledWindow]));
			w5.Position = 3;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.labelDeadline = new global::Gtk.Label ();
			this.labelDeadline.Name = "labelDeadline";
			this.labelDeadline.Xalign = 0F;
			this.labelDeadline.LabelProp = global::Mono.Unix.Catalog.GetString ("Deadline:");
			this.vboxMain.Add (this.labelDeadline);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.labelDeadline]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.checkIndefinitely = new global::Gtk.CheckButton ();
			this.checkIndefinitely.CanFocus = true;
			this.checkIndefinitely.Name = "checkIndefinitely";
			this.checkIndefinitely.Label = global::Mono.Unix.Catalog.GetString ("Indefinitely");
			this.checkIndefinitely.DrawIndicator = true;
			this.checkIndefinitely.UseUnderline = true;
			this.vboxMain.Add (this.checkIndefinitely);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.checkIndefinitely]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.calendarDeadline = new global::Gtk.Calendar ();
			this.calendarDeadline.CanFocus = true;
			this.calendarDeadline.Name = "calendarDeadline";
			this.calendarDeadline.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(43));
			this.calendarDeadline.ShowWeekNumbers = true;
			this.hbox3.Add (this.calendarDeadline);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.calendarDeadline]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
			w9.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w10.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.vbox2.Add (this.buttonOk);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.vbox2.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonCancel]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox3.Add (this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox2]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vboxMain.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hbox3]));
			w14.Position = 6;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 371;
			this.DefaultHeight = 387;
			this.Show ();
			this.checkIndefinitely.Toggled += new global::System.EventHandler (this.OnCheckIndefinitelyToggled);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
		}
	}
}
