
// This file has been generated by the GUI designer. Do not modify.
namespace KPI
{
	public partial class PreferencesWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.CheckButton checkAutoremove;
		private global::Gtk.CheckButton checkExecuted;
		private global::Gtk.CheckButton checkOutdated;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label labelOlderThan;
		private global::Gtk.Entry entryOlderThan;
		private global::Gtk.Label labelDays;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.CheckButton checkHide;
		private global::Gtk.CheckButton checkShowNotifications;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KPI.PreferencesWindow
			this.Name = "KPI.PreferencesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child KPI.PreferencesWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkAutoremove = new global::Gtk.CheckButton ();
			this.checkAutoremove.CanFocus = true;
			this.checkAutoremove.Name = "checkAutoremove";
			this.checkAutoremove.Label = global::Mono.Unix.Catalog.GetString ("Autoremove old jobs");
			this.checkAutoremove.DrawIndicator = true;
			this.checkAutoremove.UseUnderline = true;
			this.vbox1.Add (this.checkAutoremove);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkAutoremove]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkExecuted = new global::Gtk.CheckButton ();
			this.checkExecuted.CanFocus = true;
			this.checkExecuted.Name = "checkExecuted";
			this.checkExecuted.Label = global::Mono.Unix.Catalog.GetString ("Executed");
			this.checkExecuted.DrawIndicator = true;
			this.checkExecuted.UseUnderline = true;
			this.vbox1.Add (this.checkExecuted);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkExecuted]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkOutdated = new global::Gtk.CheckButton ();
			this.checkOutdated.CanFocus = true;
			this.checkOutdated.Name = "checkOutdated";
			this.checkOutdated.Label = global::Mono.Unix.Catalog.GetString ("Outdated");
			this.checkOutdated.DrawIndicator = true;
			this.checkOutdated.UseUnderline = true;
			this.vbox1.Add (this.checkOutdated);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkOutdated]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelOlderThan = new global::Gtk.Label ();
			this.labelOlderThan.Name = "labelOlderThan";
			this.labelOlderThan.LabelProp = global::Mono.Unix.Catalog.GetString ("Older than");
			this.hbox1.Add (this.labelOlderThan);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelOlderThan]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryOlderThan = new global::Gtk.Entry ();
			this.entryOlderThan.WidthRequest = 1;
			this.entryOlderThan.CanFocus = true;
			this.entryOlderThan.Name = "entryOlderThan";
			this.entryOlderThan.IsEditable = true;
			this.entryOlderThan.MaxLength = 3;
			this.entryOlderThan.InvisibleChar = '•';
			this.hbox1.Add (this.entryOlderThan);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryOlderThan]));
			w5.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelDays = new global::Gtk.Label ();
			this.labelDays.Name = "labelDays";
			this.labelDays.LabelProp = global::Mono.Unix.Catalog.GetString ("days");
			this.hbox1.Add (this.labelDays);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelDays]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w7.Position = 3;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkHide = new global::Gtk.CheckButton ();
			this.checkHide.CanFocus = true;
			this.checkHide.Name = "checkHide";
			this.checkHide.Label = global::Mono.Unix.Catalog.GetString ("checkbutton6");
			this.checkHide.DrawIndicator = true;
			this.checkHide.UseUnderline = true;
			this.vbox1.Add (this.checkHide);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkHide]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkShowNotifications = new global::Gtk.CheckButton ();
			this.checkShowNotifications.CanFocus = true;
			this.checkShowNotifications.Name = "checkShowNotifications";
			this.checkShowNotifications.Label = global::Mono.Unix.Catalog.GetString ("Show notifications");
			this.checkShowNotifications.DrawIndicator = true;
			this.checkShowNotifications.UseUnderline = true;
			this.vbox1.Add (this.checkShowNotifications);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkShowNotifications]));
			w11.Position = 6;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w12.Position = 7;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment2]));
			w13.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.WidthRequest = 90;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.hbox2.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonCancel]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.WidthRequest = 90;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.hbox2.Add (this.buttonOk);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonOk]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w16.Position = 8;
			w16.Expand = false;
			w16.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 221;
			this.Show ();
		}
	}
}
