
// This file has been generated by the GUI designer. Do not modify.
namespace KPI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action mbMenuFile;
		private global::Gtk.Action mbActionExit;
		private global::Gtk.Action mbMenuEdit;
		private global::Gtk.ToggleAction mbActionShowToolbar;
		private global::Gtk.Action preferencesAction;
		private global::Gtk.Action JobAction;
		private global::Gtk.Action addAction;
		private global::Gtk.Action editAction;
		private global::Gtk.Action removeAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action tbActionCreate;
		private global::Gtk.Action tbActionEdit;
		private global::Gtk.Action tbActionRemove;
		private global::Gtk.Action tbActionExit;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar menubarMain;
		private global::Gtk.Toolbar toolbarMain;
		private global::Gtk.ScrolledWindow scrolledwinMain;
		private global::Gtk.TreeView treeviewMain;
		private global::Gtk.Statusbar statusbarMain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KPI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.mbMenuFile = new global::Gtk.Action ("mbMenuFile", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.mbMenuFile.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.mbMenuFile, null);
			this.mbActionExit = new global::Gtk.Action ("mbActionExit", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.mbActionExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.mbActionExit, null);
			this.mbMenuEdit = new global::Gtk.Action ("mbMenuEdit", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.mbMenuEdit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.mbMenuEdit, null);
			this.mbActionShowToolbar = new global::Gtk.ToggleAction ("mbActionShowToolbar", global::Mono.Unix.Catalog.GetString ("Show toolbar"), null, null);
			this.mbActionShowToolbar.Active = true;
			this.mbActionShowToolbar.ShortLabel = global::Mono.Unix.Catalog.GetString ("Show toolbar");
			w1.Add (this.mbActionShowToolbar, null);
			this.preferencesAction = new global::Gtk.Action ("preferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences..."), null, "gtk-preferences");
			this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.preferencesAction, null);
			this.JobAction = new global::Gtk.Action ("JobAction", global::Mono.Unix.Catalog.GetString ("Job"), null, null);
			this.JobAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Job");
			w1.Add (this.JobAction, null);
			this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("Create..."), null, "gtk-add");
			this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create");
			w1.Add (this.addAction, null);
			this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Edit..."), null, "gtk-edit");
			this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.editAction, null);
			this.removeAction = new global::Gtk.Action ("removeAction", global::Mono.Unix.Catalog.GetString ("Remove..."), null, "gtk-remove");
			this.removeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove");
			w1.Add (this.removeAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About..."), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.tbActionCreate = new global::Gtk.Action ("tbActionCreate", global::Mono.Unix.Catalog.GetString ("Create"), null, "gtk-add");
			this.tbActionCreate.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create");
			w1.Add (this.tbActionCreate, null);
			this.tbActionEdit = new global::Gtk.Action ("tbActionEdit", global::Mono.Unix.Catalog.GetString ("Edit"), null, "gtk-edit");
			this.tbActionEdit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.tbActionEdit, null);
			this.tbActionRemove = new global::Gtk.Action ("tbActionRemove", global::Mono.Unix.Catalog.GetString ("Remove"), null, "gtk-remove");
			this.tbActionRemove.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove");
			w1.Add (this.tbActionRemove, null);
			this.tbActionExit = new global::Gtk.Action ("tbActionExit", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
			this.tbActionExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.tbActionExit, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "KPI.MainWindow";
			this.Title = "";
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Dialog);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child KPI.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'><menu name='mbMenuFile' action='mbMenuFile'><menuitem name='mbActionExit' action='mbActionExit'/></menu><menu name='mbMenuEdit' action='mbMenuEdit'><menuitem name='mbActionShowToolbar' action='mbActionShowToolbar'/><separator/><menuitem name='preferencesAction' action='preferencesAction'/></menu><menu name='JobAction' action='JobAction'><menuitem name='addAction' action='addAction'/><menuitem name='editAction' action='editAction'/><menuitem name='removeAction' action='removeAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
			this.menubarMain.Name = "menubarMain";
			this.vboxMain.Add (this.menubarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbarMain'><toolitem name='tbActionCreate' action='tbActionCreate'/><toolitem name='tbActionEdit' action='tbActionEdit'/><toolitem name='tbActionRemove' action='tbActionRemove'/><separator/><toolitem name='tbActionExit' action='tbActionExit'/></toolbar></ui>");
			this.toolbarMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbarMain")));
			this.toolbarMain.Name = "toolbarMain";
			this.toolbarMain.ShowArrow = false;
			this.vboxMain.Add (this.toolbarMain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.toolbarMain]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.scrolledwinMain = new global::Gtk.ScrolledWindow ();
			this.scrolledwinMain.CanFocus = true;
			this.scrolledwinMain.Name = "scrolledwinMain";
			this.scrolledwinMain.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwinMain.Gtk.Container+ContainerChild
			this.treeviewMain = new global::Gtk.TreeView ();
			this.treeviewMain.CanFocus = true;
			this.treeviewMain.Name = "treeviewMain";
			this.scrolledwinMain.Add (this.treeviewMain);
			this.vboxMain.Add (this.scrolledwinMain);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.scrolledwinMain]));
			w5.Position = 2;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.statusbarMain = new global::Gtk.Statusbar ();
			this.statusbarMain.Name = "statusbarMain";
			this.statusbarMain.Spacing = 6;
			this.vboxMain.Add (this.statusbarMain);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbarMain]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 476;
			this.DefaultHeight = 328;
			this.Show ();
			this.mbActionExit.Activated += new global::System.EventHandler (this.OnExit);
			this.mbActionShowToolbar.Toggled += new global::System.EventHandler (this.ShowToolbar);
			this.preferencesAction.Activated += new global::System.EventHandler (this.OnActionPreferencesActivated);
			this.addAction.Activated += new global::System.EventHandler (this.OnCreateActivated);
			this.editAction.Activated += new global::System.EventHandler (this.OnActionEditActivated);
			this.removeAction.Activated += new global::System.EventHandler (this.OnActionRemoveActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnActionAboutActivated);
			this.tbActionCreate.Activated += new global::System.EventHandler (this.OnCreateActivated);
			this.tbActionEdit.Activated += new global::System.EventHandler (this.OnActionEditActivated);
			this.tbActionRemove.Activated += new global::System.EventHandler (this.OnActionRemoveActivated);
			this.tbActionExit.Activated += new global::System.EventHandler (this.OnExit);
		}
	}
}
