
// This file has been generated by the GUI designer. Do not modify.
namespace KPI
{
	public partial class StartupWindow
	{
		private global::Gtk.Fixed fixedMain;
		private global::Gtk.Image imageBackground;
		private global::Gtk.Label labelAppNameFull;
		private global::Gtk.Label labelAuthor;
		private global::Gtk.Label labelStatus;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KPI.StartupWindow
			this.Name = "KPI.StartupWindow";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child KPI.StartupWindow.Gtk.Container+ContainerChild
			this.fixedMain = new global::Gtk.Fixed ();
			this.fixedMain.Name = "fixedMain";
			this.fixedMain.HasWindow = false;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.imageBackground = new global::Gtk.Image ();
			this.imageBackground.Name = "imageBackground";
			this.imageBackground.Xalign = 0F;
			this.imageBackground.Yalign = 0F;
			this.imageBackground.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("KPI.Resources.bg.png");
			this.fixedMain.Add (this.imageBackground);
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.labelAppNameFull = new global::Gtk.Label ();
			this.labelAppNameFull.Name = "labelAppNameFull";
			this.labelAppNameFull.LabelProp = global::Mono.Unix.Catalog.GetString ("appnamefull");
			this.fixedMain.Add (this.labelAppNameFull);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.labelAppNameFull]));
			w2.X = 10;
			w2.Y = 10;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.labelAuthor = new global::Gtk.Label ();
			this.labelAuthor.Name = "labelAuthor";
			this.labelAuthor.LabelProp = global::Mono.Unix.Catalog.GetString ("author");
			this.fixedMain.Add (this.labelAuthor);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.labelAuthor]));
			w3.X = 10;
			w3.Y = 65;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.labelStatus = new global::Gtk.Label ();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("status");
			this.fixedMain.Add (this.labelStatus);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.labelStatus]));
			w4.X = 10;
			w4.Y = 215;
			this.Add (this.fixedMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 320;
			this.DefaultHeight = 240;
			this.Show ();
		}
	}
}
